---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ajodanwe/public_html/masjid/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp vite.config.js $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH

    